[build]
  publish = "."
  command = "node build-music-index.js"

[[headers]]
  for = "/data/*"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "no-store"

[[headers]]
  for = "/media/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
